#!/usr/bin/env python3
"""Produce Results/test_suite/RESULTS_SUMMARY.md.

Aggregates the outputs of every per-session analysis script into a single
report formatted for copy-pasting into the manuscript discussion section.

Usage: python analysis/compile_test_suite_report.py
No arguments — reads the catalog and whichever per-session CSVs exist.
"""
import os
import sys
import textwrap

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _helpers import RESULTS_ROOT, TEST_SUITE_ROOT, load_catalog

OUT = os.path.join(TEST_SUITE_ROOT, "RESULTS_SUMMARY.md")


def section(title, body):
    return f"\n## {title}\n\n{body.strip()}\n"


def read_csv_if_exists(path):
    return pd.read_csv(path) if os.path.exists(path) else None


def main() -> int:
    parts = ["# Test-suite results summary\n\nAuto-generated by analysis/compile_test_suite_report.py."]
    cat = load_catalog()
    done = cat[cat["status"] == "done"]
    pending = cat[cat["status"] == "pending"]
    parts.append(section(
        "Run accounting",
        f"- Done: {len(done)} / {len(cat)} runs\n- Pending: {len(pending)} runs\n"
    ))

    for csv_name, label in [
        ("scaling_tf2_summary.csv",            "TaylorF2 heterodyned scaling (Session 01)"),
        ("repeat_variance_aggregate.csv",      "Repeat-run variance (Session 02)"),
        ("unhet_scaling_summary.csv",          "Unheterodyned scaling (Sessions 03/04/05)"),
        ("gw150914_waveform_comparison.csv",   "GW150914 waveform faithfulness (Session 06)"),
        ("gw170817_waveform_comparison.csv",   "GW170817 precessing / alt-tidal (Session 07)"),
        ("num_delete_sweep_summary.csv",       "num_delete sweep (Session 08)"),
        ("het_bins_sweep_summary.csv",         "Heterodyne-bin sweep (Session 09)"),
        ("bimodality_summary.csv",             "d_L–iota bimodality (Session 10)"),
        ("scaling_20k_anomaly.csv",            "n_live=20000 anomaly (Session 11)"),
        ("psd_sensitivity_summary.csv",        "PSD sensitivity (Session 05 extras)"),
    ]:
        df = read_csv_if_exists(os.path.join(RESULTS_ROOT, csv_name))
        if df is None:
            parts.append(section(label, "(not yet produced — run the corresponding analysis script)"))
            continue
        parts.append(section(label, "```\n" + df.to_string(index=False) + "\n```"))

    prior_hint_md = textwrap.dedent("""
        Session H (prior-only q-diagnostic) does not produce a summary CSV; run
        `python mnras_paper/test_suite/analysis/analyze_q_prior.py` and copy its
        stdout into the manuscript's discussion of the LVK q-deficit.
    """).strip()
    parts.append(section("Prior-only q-diagnostic (Session H)", prior_hint_md))

    with open(OUT, "w") as fh:
        fh.write("\n".join(parts))
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
